### ISSUE TITLE
Arrow positions are not synced

### ISSUE THREAD

**Issue by fornclake** [fornclake/TetraForce#3]
When an arrow is spawned by a Knawblin or player, it spawns wherever the entity was on each player's screen. This means if positions aren't perfectly synchronized, the arrow might be in two different places on both screens.

This doesn't matter with the Knawblins quite as much because they are stationary when they fire, so they'll probably be in the correct location. However, this is not the case with players that can move around.

**Comment by asheraryam** [comment]
NPCs should be synced to the master host (which is set by default anyway).

The idea is that even if they are out of sync, the NPC on the master machine would be considered the correct one and *force* the others to move into place.

In general it's easiest to make everything have its master set to the host machine, instead of doing `is_network_master` to check whether the player agent should take input, you would use a slightly modified approach.

For example:

in player.gd
```
var player_id
func is_local_controller():
	return get_tree().get_network_unique_id() == player_id
```

in player spawner
```
puppet func spawn_player(spawn_pos, id):
	var player = Player.instance()
	
	player.name = String(id) # Important
	player.player_id = id
#	player.set_network_master(id) # This is NOT done, contrary to the official tutorials, because we want to main host to have authority over everything.
	
	$Players.add_child(player)
	
	player.global_transform.origin = spawn_pos
```

**Comment by asheraryam** [comment]
I found this great tutorial that's probably the best resource on godot multiplayer.

https://gitlab.com/menip/godot-multiplayer-tutorials/blob/master/NetworkingBasics.md

Scroll to the big table with "Use case" in it (or ctrl +f to find it). This explains when you should use master/puppet/ etc, and generally I only use 2 kinds of methods: Remote methods on the host that other players can call, and Puppet methods on the non-host players that can only be called by the host master.

**Comment by asheraryam** [comment]
Note that it can still remain fully peer-to-peer but there will be an extra verification layer to make sure everything stays in sync. So players send to each other and to the host, and if the host decides things need syncing it will send to all players to do so.

For most games this will not cause any extra network usage since the host needs to receive that data anyway, and it will only send correction data if something is wrong.

**Comment by fornclake** [comment]
Yeah, currently we have the host changing from room to room and they handle enemies. There's issue with the item spawning code however which was causing issues, so I scrapped it and decided not to sync. I will take a look at that resource and try again later.
